# Jupyter Book Configuration
title: Laboratorios MongoDB – ITVH (Jupyter Book)
author: José Juan Ulín (ITV)
logo: null
only_build_toc_files: true

sphinx:
  extra_extensions:
    - sphinx_copybutton

html:
  use_repository_button: true

repository:
  url: https://github.com/ulinjr/itvh-mongodb-labs
  path_to_book: ""
  branch: main

launch_buttons:
  colab_url: "https://colab.research.google.com"
  thebe: false

copybutton:
  selector: "div.highlight pre"
  remove_prompts: true
  copy_empty_lines: false
